name: "Potion of Weakness"
description: "Validate the code test coverage"
inputs:
  coverageFile:
    description: "File containing tests values"
    required: true
    default: "test_coverage.txt"
  outputs:
    time:
      description: "Time in seconds since epoch"
runs:
  using: "node12"
  main: "index.js"