name: "Potion of Weakness"
description: "Validate the code test coverage"
inputs:
  file:
    description: "File containing tests values"
    required: true
    default: "something"
  modified_files:
    description: "Files that were modified at this pr"
    required: true
    default: []    
  outputs:
    time:
      description: "Time in seconds since epoch"
runs:
  using: "node12"
  main: "index.js"