name: Test My Action

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: My First Action
    steps:
      - name: Getting Files
        uses: actions/checkout@v2
      - name: Get specific changed files
            id: changed-files-specific
            uses: tj-actions/changed-files@v25
            with:
              separator: ";"
              files: |
                **/*.ex
                **/*.exs
      - name: List all added files
              run: |
                for file in ${{ steps.changed-files.outputs.added_files }}; do
                  echo "$file was added"
                done                
      - name: Gosta
        id: achabom
        uses: luizloja/potion-of-weakness@main
        with: 
          file: "test_coverage.txt" 
