name: Test My Action

on:
  push:
    branches: [ main, test-main-2 ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: My First Action
    steps:
      - name: Getting Files
        uses: actions/checkout@v2
      # - name: Get specific changed files
      #   id: changed
      #   uses: jitterbit/get-changed-files@v1
      #   with:
      #     format: 'csv'
            
      # - name: List all added files
      #   run: |
      #     for file in ${{ steps.changed.outputs.added_modified }}; do
      #       echo "$file was added"
      #     done                
      - name: Gosta
        id: achabom
        uses: luizloja/potion-of-weakness@main
        with: 
          coverageFile: "test_coverage.txt" 
          minimalTestCoverage: 70
